In [63]:
import numpy as np

np.random.seed(123)

In [64]:
N = 20
d1 = np.random.rand(N) * (1 + pow(10,-5) * np.random.rand())
d2 = np.random.rand(N) * (1 + pow(10,-5) * np.random.rand())
d3 = np.random.rand(N) * (1 + pow(10,-5) * np.random.rand())
d4 = np.random.rand(N) * (1 + pow(10,-5) * np.random.rand())
d5 = d1 - d2 + d3 

In [65]:
data = np.column_stack([d1,d2,d3,d4,d5])
data

array([[ 0.6964736 ,  0.84943278,  0.31728746,  0.67469168,  0.16432829],
       [ 0.28614115,  0.72445616,  0.4148288 ,  0.84234571, -0.02348621],
       [ 0.22685289,  0.61102422,  0.86631457,  0.08319531,  0.48214325],
       [ 0.55131827,  0.72244422,  0.25045693,  0.76368581,  0.07933098],
       [ 0.71947353,  0.32295929,  0.48303728,  0.24366732,  0.87955153],
       [ 0.42310914,  0.36178907,  0.98556594,  0.19422372,  1.04688601],
       [ 0.98077042,  0.22826349,  0.51948837,  0.57245918,  1.27199529],
       [ 0.68483408,  0.29371439,  0.61289836,  0.09571289,  1.00401805],
       [ 0.48093495,  0.63097685,  0.12062942,  0.88533027, -0.02941248],
       [ 0.39212001,  0.09210505,  0.82634596,  0.62725141,  1.12636092],
       [ 0.34318019,  0.43370167,  0.6030639 ,  0.72341917,  0.51254242],
       [ 0.72905433,  0.43086326,  0.54507141,  0.01612927,  0.84326248],
       [ 0.43857503,  0.49368567,  0.34276598,  0.59443419,  0.28765533],
       [ 0.05967828,  0.42583078,  0.3

In [66]:
svd = np.linalg.svd(data)
U = svd.U
V_t = svd.Vh
S = np.diag(svd.S)

print(np.round(U,decimals=3),end="\n\n")
print(np.round(V_t,decimals=5),end="\n\n")
print(np.round(S,decimals=5),end="\n\n")

[[-0.223  0.255 -0.187 -0.307  0.813  0.198  0.016 -0.012 -0.097 -0.047
   0.05  -0.071 -0.006  0.061  0.017 -0.072  0.109 -0.019  0.121  0.017]
 [-0.182  0.336 -0.043  0.128 -0.065  0.071  0.303  0.158 -0.238  0.312
  -0.047  0.056 -0.124 -0.222 -0.004  0.105 -0.408 -0.535 -0.04  -0.141]
 [-0.202 -0.016  0.489 -0.077  0.214 -0.434  0.123 -0.092  0.271 -0.423
  -0.177 -0.006  0.062 -0.083 -0.061 -0.103 -0.35  -0.103 -0.113 -0.05 ]
 [-0.193  0.279 -0.228 -0.121 -0.18   0.012 -0.341  0.067 -0.324 -0.408
  -0.319  0.205 -0.192 -0.195  0.034  0.104 -0.053  0.268 -0.28  -0.097]
 [-0.235 -0.181 -0.117 -0.17  -0.086 -0.199 -0.384 -0.334 -0.124  0.263
   0.029 -0.424 -0.154  0.05  -0.212 -0.327 -0.018 -0.195 -0.181 -0.223]
 [-0.273 -0.231  0.316  0.135 -0.061  0.815 -0.057 -0.098  0.068 -0.155
  -0.072 -0.072 -0.007 -0.015 -0.056 -0.099 -0.103 -0.026 -0.078 -0.052]
 [-0.316 -0.262 -0.402  0.015 -0.125 -0.052  0.716 -0.13  -0.056 -0.176
  -0.065 -0.092 -0.054  0.038 -0.047 -0.115  0.113  0.18  

In [67]:
z = np.zeros((np.shape(svd.U)[1]-np.shape(svd.S)[0],np.shape(svd.S)[0]))
S = np.vstack([S,z])
S[4,4] = 0

In [68]:
result = U @ S @ V_t
result

array([[ 0.6964736 ,  0.84943278,  0.31728746,  0.67469168,  0.16432829],
       [ 0.28614115,  0.72445616,  0.4148288 ,  0.84234571, -0.02348621],
       [ 0.22685289,  0.61102422,  0.86631457,  0.08319531,  0.48214325],
       [ 0.55131827,  0.72244422,  0.25045693,  0.76368581,  0.07933098],
       [ 0.71947353,  0.32295929,  0.48303728,  0.24366732,  0.87955153],
       [ 0.42310914,  0.36178907,  0.98556594,  0.19422372,  1.04688601],
       [ 0.98077042,  0.22826349,  0.51948837,  0.57245918,  1.27199529],
       [ 0.68483408,  0.29371439,  0.61289836,  0.09571289,  1.00401805],
       [ 0.48093495,  0.63097685,  0.12062942,  0.88533027, -0.02941248],
       [ 0.39212001,  0.09210505,  0.82634596,  0.62725141,  1.12636092],
       [ 0.34318019,  0.43370167,  0.6030639 ,  0.72341917,  0.51254242],
       [ 0.72905433,  0.43086326,  0.54507141,  0.01612927,  0.84326248],
       [ 0.43857503,  0.49368567,  0.34276598,  0.59443419,  0.28765533],
       [ 0.05967828,  0.42583078,  0.3

In [69]:
difference = data-result
frobenius_norm = np.linalg.norm(difference,"fro")
frobenius_norm

3.653965132731278e-15

In [70]:
for i in range(1,5):
    x = np.zeros((N,5))
    x[:i,:i] = S[:i,:i]
    result = U @ x @ V_t
    
    print("Frobenius Norm for Rank 1 approximation for r =",i,end=" ")
    print(np.linalg.norm(data - result,"fro"))

    print("Two Norm for Rank 1 approximation for r =",i,end=" ")
    print(np.linalg.norm(data - result,2),end="\n\n")

Frobenius Norm for Rank 1 approximation for r = 1 2.693105531061557
Two Norm for Rank 1 approximation for r = 1 2.2679436927572665

Frobenius Norm for Rank 1 approximation for r = 2 1.452325310637008
Two Norm for Rank 1 approximation for r = 2 1.1432518287734297

Frobenius Norm for Rank 1 approximation for r = 3 0.895669617617507
Two Norm for Rank 1 approximation for r = 3 0.8956696176175069

Frobenius Norm for Rank 1 approximation for r = 4 3.653965132731278e-15
Two Norm for Rank 1 approximation for r = 4 2.9340936880048896e-15



***

In [71]:
N = 20
d1_2 = np.random.rand(N) * (1 + pow(10,-5) * np.random.rand())
d2_2 = np.random.rand(N) * (1 + pow(10,-5) * np.random.rand())
d3_2 = np.random.rand(N)* (1 + pow(10,-5) * np.random.rand())
d4_2 = 4 * d1_2 - 3 *  d2_2 + 2 * d3_2
d5_2 = d1_2 - d2_2 + d3_2

In [72]:
data_2 = np.column_stack([d1_2,d2_2,d3_2,d4_2,d5_2])
data_2

array([[ 9.25135468e-01,  6.61570844e-01,  2.57543975e-01,
         2.23091729e+00,  5.21108599e-01],
       [ 8.41672707e-01,  8.46514552e-01,  5.64363230e-01,
         1.95587363e+00,  5.59521385e-01],
       [ 3.57398717e-01,  5.53262787e-01,  8.06974671e-01,
         1.38375585e+00,  6.11110601e-01],
       [ 4.35916042e-02,  8.54460892e-01,  3.94372980e-01,
        -1.60027030e+00, -4.16496308e-01],
       [ 3.04769055e-01,  3.84841597e-01,  7.31078459e-01,
         1.52670835e+00,  6.51005917e-01],
       [ 3.98186964e-01,  3.16791013e-01,  1.61070209e-01,
         9.64515235e-01,  2.42466160e-01],
       [ 7.04961100e-01,  3.54268160e-01,  6.00703024e-01,
         2.95844597e+00,  9.51395964e-01],
       [ 9.95361687e-01,  1.71083512e-01,  8.65870882e-01,
         5.19993798e+00,  1.69014906e+00],
       [ 3.55916012e-01,  8.29120790e-01,  9.83528906e-01,
         9.03359488e-01,  5.10324127e-01],
       [ 7.62550269e-01,  3.38674177e-01,  7.93663792e-02,
         2.19291130e+00

In [73]:
svd = np.linalg.svd(data_2)
U = svd.U
V_t = svd.Vh
S = np.diag(svd.S)

print(np.round(U,decimals=3),end="\n\n")
print(np.round(V_t,decimals=5),end="\n\n")
print(np.round(S,decimals=5),end="\n\n")

[[-0.235  0.13  -0.408  0.424  0.268 -0.163 -0.138 -0.352  0.081 -0.301
  -0.208 -0.309 -0.052 -0.058 -0.209 -0.219  0.014 -0.079 -0.019  0.01 ]
 [-0.217  0.233 -0.207 -0.744 -0.165 -0.048 -0.071 -0.029 -0.235 -0.167
  -0.069 -0.088 -0.096  0.126 -0.261 -0.166 -0.118 -0.098 -0.055 -0.156]
 [-0.162  0.189  0.238  0.275 -0.041  0.06  -0.001 -0.155 -0.37   0.341
  -0.032  0.14  -0.269 -0.186 -0.028 -0.135 -0.257  0.056 -0.296 -0.469]
 [ 0.136  0.393  0.067  0.215 -0.291 -0.126 -0.196  0.598 -0.123 -0.032
  -0.196 -0.233  0.109 -0.127 -0.026 -0.063  0.264 -0.255 -0.043 -0.038]
 [-0.171  0.12   0.248 -0.009 -0.134 -0.021 -0.299 -0.273 -0.135 -0.214
  -0.03   0.002  0.144 -0.183  0.361  0.307 -0.377 -0.391  0.153  0.224]
 [-0.103  0.071 -0.149  0.07  -0.098  0.963 -0.04   0.026  0.024 -0.061
  -0.044 -0.07   0.025 -0.015 -0.018 -0.019  0.044 -0.042  0.014  0.032]
 [-0.309  0.028 -0.023  0.072 -0.268 -0.062  0.862  0.004 -0.013 -0.081
  -0.091 -0.105  0.058 -0.121  0.082  0.035 -0.008 -0.154 

In [74]:
z = np.zeros((np.shape(svd.U)[1]-np.shape(svd.S)[0],np.shape(svd.S)[0]))
S = np.vstack([S,z])
S[3,3] , S[4,4] = 0 , 0

In [75]:
result = U @ S @ V_t
result

array([[ 9.25135468e-01,  6.61570844e-01,  2.57543975e-01,
         2.23091729e+00,  5.21108599e-01],
       [ 8.41672707e-01,  8.46514552e-01,  5.64363230e-01,
         1.95587363e+00,  5.59521385e-01],
       [ 3.57398717e-01,  5.53262787e-01,  8.06974671e-01,
         1.38375585e+00,  6.11110601e-01],
       [ 4.35916042e-02,  8.54460892e-01,  3.94372980e-01,
        -1.60027030e+00, -4.16496308e-01],
       [ 3.04769055e-01,  3.84841597e-01,  7.31078459e-01,
         1.52670835e+00,  6.51005917e-01],
       [ 3.98186964e-01,  3.16791013e-01,  1.61070209e-01,
         9.64515235e-01,  2.42466160e-01],
       [ 7.04961100e-01,  3.54268160e-01,  6.00703024e-01,
         2.95844597e+00,  9.51395964e-01],
       [ 9.95361687e-01,  1.71083512e-01,  8.65870882e-01,
         5.19993798e+00,  1.69014906e+00],
       [ 3.55916012e-01,  8.29120790e-01,  9.83528906e-01,
         9.03359488e-01,  5.10324127e-01],
       [ 7.62550269e-01,  3.38674177e-01,  7.93663792e-02,
         2.19291130e+00

In [76]:
difference = data_2-result
frobenius_norm = np.linalg.norm(difference,"fro")
frobenius_norm

2.3720978232433618e-15

In [77]:
for i in range(1,5):
    x = np.zeros((N,5))
    x[:i,:i] = S[:i,:i]
    result = U @ x @ V_t
    print("Frobenius Norm for Rank 1 approximation for r =",i,end=" ")
    print(np.linalg.norm(data_2 - result,"fro"))

    print("Two Norm for Rank 1 approximation for r =",i,end=" ")
    print(np.linalg.norm(data_2 - result,2),end="\n\n")

Frobenius Norm for Rank 1 approximation for r = 1 3.4452322674799922
Two Norm for Rank 1 approximation for r = 1 3.1817772360786107

Frobenius Norm for Rank 1 approximation for r = 2 1.321332281016885
Two Norm for Rank 1 approximation for r = 2 1.3213322810168848

Frobenius Norm for Rank 1 approximation for r = 3 2.3720978232433618e-15
Two Norm for Rank 1 approximation for r = 3 1.9145309593446493e-15

Frobenius Norm for Rank 1 approximation for r = 4 2.3720978232433618e-15
Two Norm for Rank 1 approximation for r = 4 1.9145309593446493e-15

