In [2]:
import numpy as np
import math

In [3]:
m = np.array([[4,1,0.5,0.5],[4,1,-0.5,-0.5],[4,-2,0,0]])

In [4]:
svd = np.linalg.svd(m)

In [5]:
print(svd.U)
print(svd.S)
print(svd.Vh)

print(np.round(svd.U.T @ m @ svd.Vh.T,decimals=4))

[[ 5.77350269e-01  4.08248290e-01  7.07106781e-01]
 [ 5.77350269e-01  4.08248290e-01 -7.07106781e-01]
 [ 5.77350269e-01 -8.16496581e-01 -2.14553655e-16]]
[6.92820323 2.44948974 1.        ]
[[ 1.00000000e+00  8.32667268e-17 -2.77555756e-17 -2.77555756e-17]
 [-7.27735153e-18  1.00000000e+00  9.57638507e-18  9.57638507e-18]
 [ 1.58196364e-17  2.34444018e-17  7.07106781e-01  7.07106781e-01]
 [ 1.11626586e-18 -4.93423030e-17 -7.07106781e-01  7.07106781e-01]]
[[ 6.9282  0.     -0.      0.    ]
 [-0.      2.4495 -0.     -0.    ]
 [ 0.      0.      1.      0.    ]]


In [6]:
m_mt = m @ m.T
mt_m = m.T @ m

print(m_mt)
print(mt_m)

[[17.5 16.5 14. ]
 [16.5 17.5 14. ]
 [14.  14.  20. ]]
[[48.   0.   0.   0. ]
 [ 0.   6.   0.   0. ]
 [ 0.   0.   0.5  0.5]
 [ 0.   0.   0.5  0.5]]


In [7]:
print(np.linalg.eig(m_mt).eigenvalues)
print(np.linalg.eig(m_mt).eigenvectors)
print(np.linalg.eig(mt_m).eigenvectors)
print(np.linalg.eig(mt_m).eigenvalues)

[48.  1.  6.]
[[-5.77350269e-01 -7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  7.07106781e-01 -4.08248290e-01]
 [-5.77350269e-01  9.97620368e-17  8.16496581e-01]]
[[ 0.          0.          1.          0.        ]
 [ 0.          0.          0.          1.        ]
 [ 0.70710678 -0.70710678  0.          0.        ]
 [ 0.70710678  0.70710678  0.          0.        ]]
[1.00000000e+00 1.11022302e-16 4.80000000e+01 6.00000000e+00]


In [8]:
test = np.array([[30.5,-16.5,-14],[-16.5,30.5,-14],[-14,-14,28]])
test

array([[ 30.5, -16.5, -14. ],
       [-16.5,  30.5, -14. ],
       [-14. , -14. ,  28. ]])

In [9]:
test[0] = test[0] / 30.5
test

array([[  1.        ,  -0.54098361,  -0.45901639],
       [-16.5       ,  30.5       , -14.        ],
       [-14.        , -14.        ,  28.        ]])

In [10]:
test[1] = test[1] + test[0] * (16.5)
test[2] = test[2] + test[0] * (14)
test

array([[  1.        ,  -0.54098361,  -0.45901639],
       [  0.        ,  21.57377049, -21.57377049],
       [  0.        , -21.57377049,  21.57377049]])

In [11]:
test[1] = test[1] / test[1,1]
test

array([[  1.        ,  -0.54098361,  -0.45901639],
       [  0.        ,   1.        ,  -1.        ],
       [  0.        , -21.57377049,  21.57377049]])

In [12]:
test[2] = test[2] - test[1] * test[2,1]
test

array([[ 1.        , -0.54098361, -0.45901639],
       [ 0.        ,  1.        , -1.        ],
       [ 0.        ,  0.        ,  0.        ]])

In [13]:
test[0] = test[0] - test[1] * test[0,1]
test

array([[ 1.,  0., -1.],
       [ 0.,  1., -1.],
       [ 0.,  0.,  0.]])

In [14]:
U = np.array([[0.577,0.4082,0.707],[0.577,0.4082,-0.707],[0.577,-0.816,0]])
V = [[1,0,0,0],[0,1,0,0],[0,0,0.707,0.707],[0,0,0.707,-0.707]]

result = np.round(U.T @ m @ V,decimals=3)
result

array([[ 6.924e+00,  0.000e+00,  0.000e+00,  0.000e+00],
       [ 2.000e-03,  2.448e+00,  0.000e+00,  0.000e+00],
       [ 0.000e+00,  0.000e+00,  1.000e+00, -0.000e+00]])

In [15]:
U[:,0] @ U[:,1]

0.00023080000000001325

In [ ]:
np.linalg.norm([[0,0,0.5,0.5],[0,0,-0.5,-0.5],[0,0,0,0]],2)

[1.00000000e+00 1.11022302e-16 0.00000000e+00]


1.0

: 